name = "gauzy"
version = "2.0.0"

description = "gauzy is a Gleam library providing flexible implementations of probabilistic data structures"
licences = ["Apache-2.0"]
repository = { type = "github", user = "leonqadirie", repo = "gauzy" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
iv = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
murmur3a = ">= 1.0.0 and < 2.0.0"
